def appMenu():
    print("\n\t|                                                                                  |") 
    print("\t|                                                                                  |") 
    print("\t|                      (1) Widely Spread Diseases                                  |")
    print("\t|                      (2) Search By Disease Type                                  |")
    print("\t|                      (3) Search By Gender                                        |")
    print("\t|                      (4) Disease and prevention                                  |")
    print("\t|                      (5) Disease and Treatment                                   |")
    print("\t|                      (6) Talk to a Doctor                                        |")
    print("\t|                      (7) Exit                                                    |")
    print("\t|                                                                                  |") 
    print("\t|                                                                                  |") 
    print("\t|                                                                                  |\n\n")
