def welcome():
    print("\n\t __________________________________________________________________________________")
    print("\t|                                                                                  |")
    print("\t|                                  WELCOME AT Medics31                             |")
    print("\t|                                                                                  |")
    print("\t|           Lorem Ipsum is simply dummy text of the printing and jfsf.             |")
    print("\t|           There are many variations of passages of Lorem Ipsum                   |")
    print("\t|           available, but the majority have suffered  alteration in               |")
    print("\t|                                                                                  |")
    print("\t|                                                                                  |")
    print("\t|            Navigation                                                            |")
    print("\t|            ----------                                                            |")
    print("\t|                                                                                  |")
    print("\t|                      (1) Widely Spread Diseases                                  |")
    print("\t|                      (2) Search By Disease Type                                  |")
    print("\t|                      (3) Search By Gender                                        |")
    print("\t|                      (4) Disease and prevention                                  |")
    print("\t|                      (5) Disease and Treatment                                   |")
    print("\t|                      (6) Talk to a Doctor                                        |")
    print("\t|                                                                                  |")
    print("\t|                                                                                  |")               
    print("\t|__________________________________________________________________________________|\n\n")