def welcome():
    print("\n\t __________________________________________________________________________________")
    print("\t|                                                                                  |")
    print("\t|                                  WELCOME AT Medics31                             |")
    print("\t|                                                                                  |")
    print("\t|           Medics31 is a medical application designed to help you                 |")
    print("\t|           search for diseases, learn about their prevention and treatment,       |")
    print("\t|           and even talk to a doctor.                                             |")
    print("\t|           Let's get started!                                                     |")
    print("\t|__________________________________________________________________________________|\n\n")